# Generated by Django 3.1.2 on 2020-10-30 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(default='none', max_length=150)),
                ('awareness', models.CharField(default='none', max_length=150)),
                ('min_price', models.CharField(default='none', max_length=150)),
                ('max_price', models.CharField(default='none', max_length=150)),
                ('time_range', models.CharField(default='none', max_length=150)),
                ('terms', models.TextField()),
                ('board', models.CharField(default='none', max_length=150)),
                ('accessories', models.CharField(default='none', max_length=150)),
                ('bed_type', models.CharField(default='none', max_length=150)),
                ('cabinet_type', models.CharField(default='none', max_length=150)),
                ('sofa_seats', models.IntegerField(blank=True, null=True)),
                ('drawal_type', models.CharField(default='none', max_length=150)),
                ('design_quotation', models.FileField(blank=True, upload_to='project/design_quotation/')),
                ('presentation_drawing', models.FileField(blank=True, upload_to='project/presentation_drawing/')),
                ('production_drawing', models.FileField(blank=True, upload_to='project/production_drawing/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=150)),
                ('phone', models.CharField(default='none', max_length=150)),
                ('email', models.CharField(default='none', max_length=150)),
                ('address', models.TextField()),
                ('client_id', models.CharField(default='none', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='none', max_length=150)),
                ('ict', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=150)),
                ('project_id', models.CharField(default='none', max_length=150)),
                ('project_type', models.CharField(default='none', max_length=150)),
                ('delivery_date', models.CharField(default='none', max_length=150)),
                ('delivery_days', models.IntegerField(default=0)),
                ('t_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(default='none', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_order', models.FileField(blank=True, upload_to='project/work_order/')),
                ('optimized_production_drawing', models.FileField(blank=True, upload_to='project/optimised_production_drawing/')),
                ('cutting_detail', models.BooleanField(blank=True, default=False)),
                ('edge_banding_detail', models.BooleanField(blank=True, default=False)),
                ('cnc_detail', models.BooleanField(blank=True, default=False)),
                ('assembly', models.BooleanField(default=False)),
                ('u_design_quotation', models.FileField(blank=True, upload_to='project/u_design_quotation/')),
                ('u_production_drawing', models.FileField(blank=True, upload_to='project/u_production_drawing/')),
                ('u_frame', models.BooleanField(default=False)),
                ('carpenter', models.BooleanField(default=False)),
                ('foaming', models.BooleanField(default=False)),
                ('tailoring', models.BooleanField(default=False)),
                ('tacking', models.BooleanField(default=False)),
                ('spray', models.BooleanField(default=False)),
                ('material_estimate', models.FileField(blank=True, upload_to='project/material_estimate/')),
                ('cleaning', models.BooleanField(default=False)),
                ('dispatch', models.BooleanField(default=False)),
                ('installation', models.BooleanField(default=False)),
                ('frame', models.BooleanField(default=False)),
                ('ict', models.BooleanField(default=False)),
                ('cutlist_stime', models.CharField(default='none', max_length=150)),
                ('materials_stime', models.CharField(default='none', max_length=150)),
                ('store_stime', models.CharField(default='none', max_length=150)),
                ('supply_stime', models.CharField(default='none', max_length=150)),
                ('cutting_stime', models.CharField(default='none', max_length=150)),
                ('edge_banding_stime', models.CharField(default='none', max_length=150)),
                ('cnc_stime', models.CharField(default='none', max_length=150)),
                ('assembly_stime', models.CharField(default='none', max_length=150)),
                ('frame_stime', models.CharField(default='none', max_length=150)),
                ('spray_stime', models.CharField(default='none', max_length=150)),
                ('carpenter_stime', models.CharField(default='none', max_length=150)),
                ('foaming_stime', models.CharField(default='none', max_length=150)),
                ('tailoring_stime', models.CharField(default='none', max_length=150)),
                ('tacking_stime', models.CharField(default='none', max_length=150)),
                ('cleaning_stime', models.CharField(default='none', max_length=150)),
                ('dispatch_stime', models.CharField(default='none', max_length=150)),
                ('installation_stime', models.CharField(default='none', max_length=150)),
                ('cutlist_rtime', models.CharField(default='none', max_length=150)),
                ('materials_rtime', models.CharField(default='none', max_length=150)),
                ('store_rtime', models.CharField(default='none', max_length=150)),
                ('supply_rtime', models.CharField(default='none', max_length=150)),
                ('cutting_rtime', models.CharField(default='none', max_length=150)),
                ('edge_banding_rtime', models.CharField(default='none', max_length=150)),
                ('cnc_rtime', models.CharField(default='none', max_length=150)),
                ('assembly_rtime', models.CharField(default='none', max_length=150)),
                ('frame_rtime', models.CharField(default='none', max_length=150)),
                ('spray_rtime', models.CharField(default='none', max_length=150)),
                ('carpenter_rtime', models.CharField(default='none', max_length=150)),
                ('foaming_rtime', models.CharField(default='none', max_length=150)),
                ('tailoring_rtime', models.CharField(default='none', max_length=150)),
                ('tacking_rtime', models.CharField(default='none', max_length=150)),
                ('cleaning_rtime', models.CharField(default='none', max_length=150)),
                ('dispatch_rtime', models.CharField(default='none', max_length=150)),
                ('installation_rtime', models.CharField(default='none', max_length=150)),
                ('brief', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.brief')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='none', max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='project/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImageConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.projectimage')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(through='project.ProjectImageConnector', to='project.ProjectImage'),
        ),
        migrations.CreateModel(
            name='MaterialEstimateConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimate', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.estimate')),
                ('material', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.material')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='materials',
            field=models.ManyToManyField(through='project.MaterialEstimateConnector', to='project.Material'),
        ),
        migrations.AddField(
            model_name='brief',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
    ]
