# Generated by Django 3.1.2 on 2020-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='u_design_rtime',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='u_design_stime',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
