# Generated by Django 3.1.2 on 2020-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_date_hour',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
