# Generated by Django 3.1.2 on 2020-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_delivery_date_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='delivery_date_hour',
        ),
        migrations.AddField(
            model_name='project',
            name='t_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
