# Generated by Django 3.1.2 on 2020-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201030_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='store_rtime',
            new_name='store_issued_rtime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='store_stime',
            new_name='store_issued_stime',
        ),
        migrations.AddField(
            model_name='project',
            name='store_requested_rtime',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='store_requested_stime',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
