# Generated by Django 3.1.2 on 2020-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201030_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supply',
            field=models.BooleanField(default=False),
        ),
    ]
