# Generated by Django 3.1.2 on 2020-11-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201102_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project_id',
            new_name='title',
        ),
    ]
