# Generated by Django 3.1.2 on 2020-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201102_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
