# Generated by Django 3.1.2 on 2020-11-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_comment_commenter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImage',
            new_name='PImage',
        ),
        migrations.RenameModel(
            old_name='ProjectImageConnector',
            new_name='ProjectPImageConnector',
        ),
    ]
