# Generated by Django 3.1.2 on 2020-11-04 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20201103_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefPImageConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brief', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.brief')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='pimage',
            name='uploader',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.DeleteModel(
            name='ProjectPImageConnector',
        ),
        migrations.AddField(
            model_name='briefpimageconnector',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.pimage'),
        ),
        migrations.AddField(
            model_name='brief',
            name='images',
            field=models.ManyToManyField(through='project.BriefPImageConnector', to='project.PImage'),
        ),
    ]
