# Generated by Django 3.1.2 on 2020-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='time_rate',
            field=models.IntegerField(default=0),
        ),
    ]
